### ISSUE TITLE
tilit.lgbt inaccessible from current 

### ISSUE THREAD

**Issue by LorenAmelang** [tiliaqt/transkit#1]
Sorry, this gets stranger...  My original post disappeared, except for the link: 
https://www.cdn77.com/tls-test/result?domain=tilia.lgbt

The title was supposed to be "tilia.lgbt inaccessible from current Chromium browser". 

I click your link at https://github.com/tiliaqt and get:

This site can’t provide a secure connectiontilia.lgbt uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.

I'm getting a deluge of those since the latest update. 

Firefox just goes directly to a search result, guess it ignores any destination that isn't as "secure" as it likes. 

The tester at the link above says: 

http://tilia.lgbt
Your website is only running on HTTP, please upgrade to HTTPS as soon as possible. 

Is your site really plain HTTP?

**Comment by LorenAmelang** [comment]
Aha! Your link says "https" and gets errors. Clicking the "http" link in my post gets: 

tilia.lgbt has been registered at Porkbun but the owner has not put up a site yet. 

They should have a secure version of their parked message!

**Comment by violetele** [comment]
Thanks for this! Like you discovered, I don’t actually have a website up at that URL quite yet. For now I’ll remove the URL from the organization page until I have some actual content there, and close this issue. Thanks again for the heads up!
